version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    # Disable version updates for npm dependencies
    # This option has no impact on security updates, which have a separate, internal limit of ten open pull requests.
    open-pull-requests-limit: 0
    schedule:
      interval: daily

  # Maintain dependencies for Gradle
  - package-ecosystem: gradle
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: daily

  # Maintain dependencies for npm
  - package-ecosystem: docker
    directory: /
    # Disable version updates for npm dependencies
    # This option has no impact on security updates, which have a separate, internal limit of ten open pull requests.
    open-pull-requests-limit: 0
    schedule:
      interval: daily

  # Maintain dependencies for GitHub actions
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: daily

